name: eux-pdf
ingress: https://eux-pdf.intern.nav.no

application:
  eux-slett-usendte-rinasaker:
    name: eux-slett-usendte-rinasaker
    namespace: eessibasis
  eux-avslutt-rinasaker:
    name: eux-avslutt-rinasaker
    namespace: eessibasis
  user-secret: eux-rina-terminator-api

cluster:
  fss: prod-fss
  gcp: prod-gcp

rina:
  endpoint: rina-ss1.adeo.no