name: eux-pdf
ingress: https://eux-pdf.intern.nav.no

application:
  eux-rina-api:
    name: eux-rina-api
    namespace: eessibasis
  user-secret: eux-rina-terminator-api

cluster:
  fss: prod-fss
  gcp: prod-gcp

rina:
  endpoint: rina-ss1.adeo.no